### ISSUE TITLE
Why does Text.Email.Parser call a parser on its intermediate results?

### ISSUE THREAD

**Issue by Lokathor** [Porges/email-validate-hs#17]
https://github.com/Porges/email-validate-hs/blob/master/src/Text/Email/Parser.hs#L68

Here, a value called `raw` is obtained based largely on the dottedAtoms parser, and then the `raw` value is then parsed a second time using domainParser. What is the reason for this? Is it to comply with some element of the spec?

Specifically, if one wanted to re-write the whole domainName parser to not use an inner parse, would that be possible in some way while giving correct results?

I've been working on a fork that adds a polymorphic version of every parser in terms of the parsers typeclasses [here](https://github.com/Lokathor/email-validate-hs), and this is the last one to go, but I'm not clear on how to write the polymorphic version because it obviously wouldn't be allowed to call a sub-parser during the process.

**Comment by bitemyapp** [comment]
_/me waves from afar_

**Comment by Porges** [comment]
The reason for this is that the email-address RFC ([5322, section 3.4.1](https://tools.ietf.org/html/rfc5322#section-3.4.1)) specifies a really loose definition for domain names, so things that the email-address RFC says are valid might not really be a valid domain.

To fix this I've added a parser for domain names that is run on the result of the domain-name parse to ensure that it really is valid by the domain name RFC(s). (Note that this is not _yet_ in a shipped version—since the change is not technically backwards compatible and I haven't quite decided what to do with it yet...)

The reason it's not simply using the domain name parser instead is that the email-address parser performs some canonicalization as a "side-effect" of parsing—it strips out comments and something called 'folding whitespace' (collectively 'CFWS'). These are valid in the input email address but not in the resulting domain name.

> Specifically, if one wanted to re-write the whole domainName parser to not use an inner parse, would that be possible in some way while giving correct results?

It would be possible to fold in the domain name parsing with the email-address version to come up with a parser that handles the CFWS, but I haven't done this yet as it was easier to show that the domain-name handling is correct when done in this manner.

To remedy this I should really just write the combined version, add some quickcheck properties to check that it does the same thing as the two-stage parse, then delete the old one :smile:

**Comment by Porges** [comment]
I think I'll have some time tonight to look at this.

**Comment by Porges** [comment]
Made the change, want to add a few more tests & I'll push it tomorrow.

**Comment by Porges** [comment]
Finally pushed this...
