### ISSUE TITLE
The package is disabled in Stackage

### ISSUE THREAD

**Issue by mrkkrp** [Porges/email-validate-hs#58]
Needs `template-haskell-2.17`. See here:

https://github.com/commercialhaskell/stackage/blob/master/build-constraints.yaml#L5267

This effectively disables a huge subtree of dependent packages.

**Comment by parsonsmatt** [comment]
@Porges do you need a hand with maintaining? I'd like to help get this and `yesod` up-to-date. Looks like @felixonmars already made all the necessary PRs to get a new version working.

**Comment by Porges** [comment]
Uploaded as v2.3.2.14.

@parsonsmatt I’ve been thinking of finding someone to hand this off to. I don’t really have the energy to maintain it (even though it’s just bumping upper bounds once a year or so…)

(Partly I also think it’s not a great solution since really you need to only `newtype Text` and to see if you can actually contact/verify the email or not. But I wrote it when I was young & dumb & first-encountering parser combinators! 😁)

**Comment by juhp** [comment]
Just noting that email-validate is back in https://www.stackage.org/nightly-2021-07-03 :tada: 
Thanks!

**Comment by Porges** [comment]
Thanks @juhp
